export const DeepLLangs = {
	Arabic: 'AR',
	Bulgarian: 'BG',
	Czech: 'CS',
	Danish: 'DA',
	German: 'DE',
	Greek: 'EL',
	English: 'EN',
	Spanish: 'ES',
	Estonian: 'ET',
	Finnish: 'FI',
	French: 'FR',
	Hungarian: 'HU',
	Indonesian: 'ID',
	Italian: 'IT',
	Japanese: 'JA',
	Korean: 'KO',
	Lithuanian: 'LT',
	Latvian: 'LV',
	Norwegian: 'NO',
	Dutch: 'NL',
	Polish: 'PL',
	Portuguese: 'PT',
	Romanian: 'RO',
	Russian: 'RU',
	Slovak: 'SK',
	Slovenian: 'SL',
	Swedish: 'SV',
	Turkish: 'TR',
	Ukrainian: 'UK',
	'Chinese (Simplified)': 'ZH',
} as const

export const GTranslateLangs = {
	Afrikaans: 'af',
	Albanian: 'sq',
	Amharic: 'am',
	Arabic: 'ar',
	Armenian: 'hy',
	Assamese: 'as',
	Aymara: 'ay',
	Azerbaijani: 'az',
	Bambara: 'bm',
	Basque: 'eu',
	Belarusian: 'be',
	Bengali: 'bn',
	Bhojpuri: 'bho',
	Bosnian: 'bs',
	Bulgarian: 'bg',
	Catalan: 'ca',
	Cebuano: 'ceb',
	Chichewa: 'ny',
	'Chinese (Simplified)': 'zh-CN',
	'Chinese (Traditional)': 'zh-TW',
	Corsican: 'co',
	Croatian: 'hr',
	Czech: 'cs',
	Danish: 'da',
	Dhivehi: 'dv',
	Dogri: 'doi',
	Dutch: 'nl',
	English: 'en',
	Esperanto: 'eo',
	Estonian: 'et',
	Ewe: 'ee',
	Filipino: 'tl',
	Finnish: 'fi',
	French: 'fr',
	Frisian: 'fy',
	Galician: 'gl',
	Georgian: 'ka',
	German: 'de',
	Greek: 'el',
	Guarani: 'gn',
	Gujarati: 'gu',
	'Haitian Creole': 'ht',
	Hausa: 'ha',
	Hawaiian: 'haw',
	Hebrew: 'iw',
	Hindi: 'hi',
	Hmong: 'hmn',
	Hungarian: 'hu',
	Icelandic: 'is',
	Igbo: 'ig',
	Ilocano: 'ilo',
	Indonesian: 'id',
	Irish: 'ga',
	Italian: 'it',
	Japanese: 'ja',
	Javanese: 'jw',
	Kannada: 'kn',
	Kazakh: 'kk',
	Khmer: 'km',
	Kinyarwanda: 'rw',
	Konkani: 'gom',
	Korean: 'ko',
	Krio: 'kri',
	'Kurdish (Kurmanji)': 'ku',
	'Kurdish (Sorani)': 'ckb',
	Kyrgyz: 'ky',
	Lao: 'lo',
	Latin: 'la',
	Latvian: 'lv',
	Lingala: 'ln',
	Lithuanian: 'lt',
	Luganda: 'lg',
	Luxembourgish: 'lb',
	Macedonian: 'mk',
	Maithili: 'mai',
	Malagasy: 'mg',
	Malay: 'ms',
	Malayalam: 'ml',
	Maltese: 'mt',
	Maori: 'mi',
	Marathi: 'mr',
	'Meiteilon (Manipuri)': 'mni-Mtei',
	Mizo: 'lus',
	Mongolian: 'mn',
	'Myanmar (Burmese)': 'my',
	Nepali: 'ne',
	Norwegian: 'no',
	'Odia (Oriya)': 'or',
	Oromo: 'om',
	Pashto: 'ps',
	Persian: 'fa',
	Polish: 'pl',
	Portuguese: 'pt',
	Punjabi: 'pa',
	Quechua: 'qu',
	Romanian: 'ro',
	Russian: 'ru',
	Samoan: 'sm',
	Sanskrit: 'sa',
	'Scots Gaelic': 'gd',
	Sepedi: 'nso',
	Serbian: 'sr',
	Sesotho: 'st',
	Shona: 'sn',
	Sindhi: 'sd',
	Sinhala: 'si',
	Slovak: 'sk',
	Slovenian: 'sl',
	Somali: 'so',
	Spanish: 'es',
	Sundanese: 'su',
	Swahili: 'sw',
	Swedish: 'sv',
	Tajik: 'tg',
	Tamil: 'ta',
	Tatar: 'tt',
	Telugu: 'te',
	Thai: 'th',
	Tigrinya: 'ti',
	Tsonga: 'ts',
	Turkish: 'tr',
	Turkmen: 'tk',
	Twi: 'ak',
	Ukrainian: 'uk',
	Urdu: 'ur',
	Uyghur: 'ug',
	Uzbek: 'uz',
	Vietnamese: 'vi',
	Welsh: 'cy',
	Xhosa: 'xh',
	Yiddish: 'yi',
	Yoruba: 'yo',
	Zulu: 'zu',
} as const

export type LangCode = string

export function targetLangsFor(
	service: 'google' | 'deepl',
): Record<string, string> {
	return service === 'deepl' ? DeepLLangs : GTranslateLangs
}

export function langNameFor(
	service: 'google' | 'deepl',
	code: string,
): string | undefined {
	const langs = targetLangsFor(service)
	const c = code.toLowerCase()
	for (const [name, value] of Object.entries(langs))
		if (value.toLowerCase() === c) return name
	return undefined
}

// DeepL codes are uppercase (EN, KO...), Google's are lowercase (en, ko...).
// Return the canonical code for the active service when `code` matches a
// language case-insensitively, so a target picked under one service keeps
// resolving under the other instead of "losing" its selection.
export function normalizeTargetCode(
	service: 'google' | 'deepl',
	code: string,
): string {
	if (!code) return code
	const langs = targetLangsFor(service)
	const c = code.toLowerCase()
	for (const value of Object.values(langs)) {
		if (value.toLowerCase() === c) return value
	}
	return code
}
